server:
  port: 7777


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

oss:
  endpoint: oss-cn-hangzhou.aliyuncs.com
  bucketName: gullimall-xgg
  accessKeyId: LTAI5tJwtpPdtQakEmwwac4B
  accessKeySecret: Zqm1O0R06ND1UYTuB8no7ihjbk0Tso

  servlet:
    multipart:
      max-file-size:
        100MB
      max-request-size:
        100MB

mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto



